### ISSUE TITLE
Fetch all students and TAs in Add TA drop down

### ISSUE THREAD

**Issue by AnuragGorkar** [MakarandPundlik/reimplementation-front-end#3]
Currently only users having role as TA are visible in the drop down to be added as TA to the course. 
Change this so that all users who are students also are visible in the drop down. Once a user selects a student to be added as a TA there should be a pop-up asking whether this students role should be update to a TA. 
If yes do so and add the student to the course as TA.

**Comment by Rutvik2598** [comment]
Created [PR](https://github.com/MakarandPundlik/reimplementation-front-end/pull/10) for these changes.

**Comment by Rutvik2598** [comment]
PR has been merged. Closing the issue.
